TAG_REGISTRY = {
    "constructor": [
        "sets_size_to_0",
    ],
    "size": [
        "returns_size",
        "returns_this_size",
    ],
    "add": [
        "grow_check_equal",
        "grow_check_goe",
        "grow_check_plus_one",
        "grow_check_other",
        "growth_check_with_size_function",
        "grow_missing",
        "grow_called_without_capacity_check",
        "array_insert_uses_size",
        "increment_size",
        "size_change_nonstandard",
        "size_no_update",
    ],
    "addAll_min": [
        "calls_add",
        "does_not_call_add",
        "increment_size",
        "size_change_nonstandard",
        "size_no_update",
    ],
    "addAll_extended": [
        "calls_add",
        "does_not_call_add",
        "increment_size",
        "size_change_nonstandard",
        "size_no_update",
        "calls_add_and_updates_size",
        "calls_add_only",
        "updates_size_directly",
        "batch_size_update",
        "per_element_size_update",
    ],
    "clear": [
        "assign_size_to_zero",
        "decrement_size",
        "size_reset_nonstandard",
        "size_not_reset",
    ],
    "contains": [
        "loop_bound_size",
        "loop_bound_data_length",
        "loop_bound_other",
        "size_mutated_in_contains",
    ],
    "containsAll": [
        "calls_contains",
        "does_not_call_contains",
        "loop_enhanced_for",
        "loop_standard_for",
        "loop_over_input_collection",
        "loop_other",
    ],
}